name: Deploy to Server

on:
  push:
    branches:
      - main  # 當 main 分支有 push 時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 獲取程式碼
        uses: actions/checkout@v3

      - name: 部署到伺服器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22  # 確保 SSH 端口是 22
          script: |
            cd /var/www/chon1034
            git pull origin main
            npm install
            systemctl restart app.js
